name: Build & Test

on:
  push:
    branches:
      - master
      - clients/**
  pull_request:
    branches:
      - master
      - clients/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
