name: Release

on:
  push:
    tags:
      - '*v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Zip
        id: zip
        run: npm run zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: ${{ steps.zip.outputs.bundle }}
